from fastapi import FastAPI, UploadFile
from model import model_pipeline
from PIL import Image

# Create FastAPI app instance.

# Note that in production we may want to disable the /docs endpoint that is generated by FastAPI by default.
# Also configure lifespan events, CORS, middleware, authentication and authorization, rate limiting, etc.
app = FastAPI(
    # docs_url=None,
    # redoc_url=None
)

# Example endpoint (to check that it is running).
@app.get("/")
def hello_world():
    return {"Hello": "World"}

# Endpoint to use model.
@app.post("/ask")
def ask(text:str, image:UploadFile):

    image = Image.open(image.file)

    result = model_pipeline(text,image)

    return {"answers": result}
